sudo: required
dist: trusty
language: node_js
node_js:
- 14
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_script:
- travis_retry npm install --global npm@latest
- travis_retry npm install --global nyc
- travis_retry npm install
script:
- npm run lint
- npm test
- npm run coverage_test
